name: Publish a NuGet package

on:
  push:
    branches:
      - main

env:
  # Configuration type to build. RelWithDebInfo keeps PDBs for the NuGet package.
  BUILD_CONFIGURATION: RelWithDebInfo

jobs:
  build:
    runs-on: windows-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_CONFIGURATION}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_CONFIGURATION}}

    - name: Add NUGET to PATH
      uses: NuGet/setup-nuget@v1.0.5

    - name: Create a package
      run: nuget pack

    - name: Publish NuGet package
      run: dotnet nuget push "Microsoft.Test.Pict.*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/microsoft/index.json --skip-duplicate
